import tkinter as tk 
root = tk.Tk() 
root.geometry("400x400")
root.title("My First GUI_Calculator-2024")
label = tk.Label(root, text="Cal!", font=('Arial', 18))
label.pack(padx=20, pady=10)
#def
def myclick():
  print("Hello World!")
##--- menu Line ----
menubar = tk.Menu(root)
filemenu = tk.Menu(menubar, tearoff=0)
filemenu.add_command(label="Close", command=myclick)
filemenu.add_separator()
filemenu.add_command(label="Close without Question", command=exit)

Switch_screens = tk.Menu(menubar, tearoff=0)
Switch_screens.add_command(label="Program", command=myclick)
Switch_screens.add_separator()
Switch_screens.add_command(label="main", command=myclick)
Switch_screens.add_separator()
Switch_screens.add_command(label="Note", command=myclick)

menubar.add_cascade(menu=filemenu, label="File")
menubar.add_cascade(menu=Switch_screens, label="Switch Screens")

root.config(menu=menubar)
##textbox
textbox = tk.Text(root, height=3, font=('Arial', 16))
textbox.pack()
##buttonFrame
buttonFrame = tk.Frame(root)
buttonFrame.columnconfigure(0, weight=1)
buttonFrame.columnconfigure(1, weight=1)
buttonFrame.columnconfigure(2, weight=1)
#row1
btn7 = tk.Button(buttonFrame, text="7", font=('Arial', 18))
btn7.grid(row=0, column=0, sticky=tk.W+tk.E)
btn8 = tk.Button(buttonFrame, text="8", font=('Arial', 18))
btn8.grid(row=0, column=1, sticky=tk.W+tk.E)
btn9 = tk.Button(buttonFrame, text="9", font=('Arial', 18))
btn9.grid(row=0, column=2, sticky=tk.W+tk.E)
btn_Del = tk.Button(buttonFrame, text="Del", font=('Arial', 18))
btn_Del.grid(row=0, column=3, sticky=tk.W+tk.E)
btn_Ac = tk.Button(buttonFrame, text="Ac", font=('Arial', 18))
btn_Ac.grid(row=0, column=4, sticky=tk.W+tk.E)
#row2
btn4 = tk.Button(buttonFrame, text="4", font=('Arial', 18))
btn4.grid(row=1, column=0, sticky=tk.W+tk.E)
btn5 = tk.Button(buttonFrame, text="5", font=('Arial', 18))
btn5.grid(row=1, column=1, sticky=tk.W+tk.E)
btn6 = tk.Button(buttonFrame, text="6", font=('Arial', 18))
btn6.grid(row=1, column=2, sticky=tk.W+tk.E)
btn_Times = tk.Button(buttonFrame, text="X", font=('Arial', 18))
btn_Times.grid(row=1, column=3, sticky=tk.W+tk.E)
btn_Divide = tk.Button(buttonFrame, text="/", font=('Arial', 18))
btn_Divide.grid(row=1, column=4, sticky=tk.W+tk.E) 
#row3 
btn1 = tk.Button(buttonFrame, text="1", font=('Arial', 18))
btn1.grid(row=2, column=0, sticky=tk.W+tk.E)
btn2 = tk.Button(buttonFrame, text="2", font=('Arial', 18))
btn2.grid(row=2, column=1, sticky=tk.W+tk.E)
btn3 = tk.Button(buttonFrame, text="3", font=('Arial', 18))
btn3.grid(row=2, column=2, sticky=tk.W+tk.E)
btn_Add  = tk.Button(buttonFrame, text="+", font=('Arial', 18))
btn_Add.grid(row=2, column=3, sticky=tk.W+tk.E)
btn_Subtract = tk.Button(buttonFrame, text="-", font=('Arial', 18))
btn_Subtract.grid(row=2, column=4, sticky=tk.W+tk.E) 
#row4 dot power X10 answer equal
btn0 = tk.Button(buttonFrame, text="0", font=('Arial', 18))
btn0.grid(row=3, column=0, sticky=tk.W+tk.E)
btn_Dot = tk.Button(buttonFrame, text=".", font=('Arial', 18))
btn_Dot.grid(row=3, column=1, sticky=tk.W+tk.E)
btn_X10 = tk.Button(buttonFrame, text="X10", font=('Arial', 18))
btn_X10.grid(row=3, column=2, sticky=tk.W+tk.E)
btn_Ans  = tk.Button(buttonFrame, text="Ans", font=('Arial', 18))
btn_Ans.grid(row=3, column=3, sticky=tk.W+tk.E)
btn_Equal = tk.Button(buttonFrame, text="=", font=('Arial', 18))
btn_Equal.grid(row=3, column=4, sticky=tk.W+tk.E) 
#row5 (empty row)
buttonFrame.pack(fill='x')


root.mainloop()